#!/bin/sh

echo "Running tests"
./bin/dev.sh test
status=$?
if [ $status != 0 ]; then
    echo "One or more tests failed! Commit cancelled."
    echo "To bypass, use the --no-verify flag."
    exit $status
fi
